[project]
name = "hosvital-solutions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pyspark>=3.5.4",
    "python-dotenv>=1.0.1",
    "vaex>=4.17.0",
]
